### ISSUE TITLE
EPIC: Reproducible Tests

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2347]
Related to the goals identified in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1522 and https://github.com/AdoptOpenJDK/openjdk-build/issues/2522, we will like to take the information from the SHA.txt file (which test jobs already create), augment it with any other information needed to rerun the exact same set of tests against a build.

This work includes:
- prototype by writing a script that can take the contents of a SHA.txt file and/or a "Rerun in Grinder link" to rerun a test job with the appropriate environment variables (input parameters) set (see https://github.com/AdoptOpenJDK/openjdk-tests/issues/2511)
- creating an AQA BoM https://github.com/AdoptOpenJDK/openjdk-tests/issues/1169 (right now is SHA.txt, but can rename to .testInfo, to align with .buildInfo naming)
- Investigate using the "Rerun in Grinder" functionality that TKG provides to be able to feed in the AQA BoM for test reproduction

**Comment by llxia** [comment]
Discussed with @smlambert , here is the overview of the workflow:
The test build (both automated and local runs) will generate a property file (similar to the current SHA.txt) to capture the SHA that we use in each repo. The property file will replace the existing SHA.txt. In the release branch, the property file will be checked into the repo. In the case of reproducing the build, this property file will be used and the test pipeline will check out the material as stated in the property file.

TODOs:

- [ ] [Accept STF sha in test pipeline](https://github.com/adoptium/aqa-tests/issues/2680)
- [ ] [Accept system test sha in test pipeline](https://github.com/adoptium/aqa-tests/issues/2887)
- [ ] [Generate property file with SHA into](https://github.com/adoptium/aqa-tests/issues/2889)
- [ ] Remove OPNEJ9_SHA in test pipeline

**Comment by smlambert** [comment]
I think we can close this as the last item in the checklist was marked optional.
