### ISSUE TITLE
Support rerun in Grinder using jck_custom with failed testcases

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4498]
Similar to [Rerun in Grinder using jdk_custom | hotspot_custom with failed testcases](https://github.com/adoptium/aqa-tests/issues/4265) we could support rerun in Grinder using jck_custom with failed testcases to ease the jck triage.
 
- [x] jck_custom support multiple testcases? https://github.com/adoptium/aqa-tests/issues/5068
- [x] parse tap file and enable rerun link in jenkins job https://github.com/adoptium/aqa-tests/issues/5105
- [x] update jck tap file format in tkg https://github.com/adoptium/TKG/issues/439

**Comment by sophia-guo** [comment]
Note: as jck_custom target is defined in runtime.api/playlsit.xml BUILD_LIST has to be either jck or jck/runtime.api
