### ISSUE TITLE
Improvements related with rerun test jobs

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5016]
Rerun test jobs was recently enabled in adoptium, which definitely helps in the latest releases. Here are some thoughts or issues we met during the releases:

- [x] for openjdk tests, rerun failed targets might cost. There might be a few test cases fail but the test target might include a few hundred of testcases. https://github.com/adoptium/aqa-tests/issues/5241
- [x] there will be new intermittent failures during the rerun test target. I.e, the former failure test cases pass in the rerun test target while other former passing test cases fail in the rerun test target. If this is the case the status of rerun build is unstable, which need manually check and hence cause extra work. Resolved by run failed testcases. https://github.com/adoptium/aqa-tests/issues/5241
- [x] rerun iteration, for now in adoptium it is set as 3. Tests will be rerun on same machine 3 times, if test targets fail once the job status will be marked as unstable. Wondered if 1 is enough as if test failures related to machine issues there is no need to rerun multiple times on same machine.
- [x] tap files are not archived to parent jobs https://github.com/adoptium/aqa-tests/issues/5015
- [ ] rerun job shows unstable, however the TEST TARGETS SUMMARY shows passed. - might be issue with tkg with iteration >1? https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.system_x86-64_mac_rerun/1/

<img width="720" alt="Screenshot 2024-01-29 at 5 33 09 PM" src="https://github.com/adoptium/aqa-tests/assets/18030625/5eab93c1-d915-4dc2-a830-267fd2dc14c1">

- [x] job with [target as *_custom ( normally grinder job) can also trigger the rerun job](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L1329). But rerun will fail if custom_target is not the default. https://github.com/adoptium/aqa-tests/issues/5388

**Comment by smlambert** [comment]
Regarding 3 versus 1, I think we will adjust to 1 at ci.adoptium.net, since often the failures we have are machine related, so there is no value to rerun 3x on the same machine.  Since this was our 'trial use' of this feature, we set it to 3 to see how it would work.

**Comment by smlambert** [comment]
After doing triage for Jan 2024 CPU - there are several updates to TRSS that I intend to add, including the list of failed openjdk testcases (just as we add to TAP files) should be tracked in the TRSS database.  Have to investigate, but this could be via changing how we configure jtreg, or actively printing out the TAP file contents to console and grabbing it at the end of the job.

**Comment by smlambert** [comment]
The rerun feature is ideally suited for environments that are more stable than ci.adoptium.net, but at the same time, if we wait for stability we may never get to try any new features.

**Comment by andrew-m-leonard** [comment]
I have been seeing extended test durations with recent builds, and have done a bit of digging into an example:
x64AlpineLinux **sanity.openjdk** is now recently taking on average about 17 hours to complete:
https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_x86-64_alpine-linux

- The main test run takes about 5hours
- Typically the following fail and are submitted for re-run: **jdk_lang_0,jdk_util_0,jdk_util_1,jdk_foreign_1** (https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_x86-64_alpine-linux_rerun/3/)
  - Of those the following always fail: jdk_util_0,jdk_util_1
- These failures cause 3 re-runs of ALL the four targets, thus effectively all **jdk_lang_0,jdk_util_0,jdk_util_1,jdk_foreign_1** get re-run 3 times
- The net effect given these 4 take up most of the sanity.openjdk duration is the whole test run is taking 4 times longer!

The issue is even worse for https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_alpine-linux/ which is typically taking 2 days if it gets that far.

I'm not sure as it currently stands that amount of extra test run time is effective?

@sophia-guo @smlambert Thoughts? Can we just re-run the "testcases" ? Should we do a blanket exclude of the failing tests?

**Comment by sxa** [comment]
Do we understand what the failures are and whether they are system specific?  That would seem to be the important thing to do the root analysis on. @Haroon-Khel are these on your radar?
I thought we only ever did one rerun for each job (but that may be wrong based on what you've said( so I'm surprised if we're getting four.

If they're taking longer than expected (and since it's happening on sanity and extended that seems likely) then it could be another example of the currency detection issues we've been seeing in containers.

**Comment by sxa** [comment]
> I'm not sure as it currently stands that amount of extra test run time is effective?

If we let it run to completion then we know we have a complete picture of the situation which should assist debugging. Also since we're only running one build a week it shouldn't cause as much of a problem as it did when we were running stuff nightly 🤷 But it did need to be understood, and probably as quite a high priority.

**Comment by andrew-m-leonard** [comment]
> > I'm not sure as it currently stands that amount of extra test run time is effective?
> 
> If we let it run to completion then we know we have a complete picture of the situation which should assist debugging. Also since we're only running one build a week it shouldn't cause as much of a problem as it did when we were running stuff nightly 🤷 But it did need to be understood, and probably as quite a high priority.

The failing tests are quite clear from the 2 re-runs, no need to wait for the subsequent 2 re-runs!

I think it does effectively highlight the problem :-) which is a bonus.
It looks like it's mainly an Alpine issue, with extended.openjdk and sanity.openjdk, which between them seem to take 2 days to run

I'm going to examine and raise an exclude of the rogue tests

**Comment by smlambert** [comment]
For the record, I have also dropped rerunIterations from 3 to 1 in our build pipeline code (via https://github.com/adoptium/ci-jenkins-pipelines/pull/929).

**Comment by sophia-guo** [comment]
For openjdk tests it should be able to rerun testcases if the failure testcases number is not big.

**Comment by smlambert** [comment]
Also related as another suggested improvement to automatic reruns is https://github.com/adoptium/aqa-tests/issues/4874 (use of EXIT_SUCCESS flag).

**Comment by smlambert** [comment]
Also related as another suggested improvement to automatic reruns is https://github.com/adoptium/aqa-tests/issues/4379 (acknowledge and skip test targets tagged as notRerun in playlist).

**Comment by sophia-guo** [comment]
Example:
[rerun 4 targets  ](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_mac_rerun/4/) takes 1.5 hours
[rerun 6 testcases ](https://ci.adoptium.net/job/Grinder/9458/) takes 43 seconds.

> https://github.com/adoptium/aqa-tests/issues/5016#issuecomment-1944289530

**Comment by sophia-guo** [comment]
If the rerun build is unstable the failed target deep history is still helpful. If the rerun build is successful then there is no need to provide the deep history of the failed targets in the rerun parents job. 

Currently if the rerun build succeeds some of the failed targets in the rerun parents job are still there( **Example A)** , but some aren't ( **Example B**).
If the rerun build is unstable some failed targets deep history are available(**Example C**) , some are not (**Example D**). Not sure why and confusing.
Example  B and C are expected behavior. Example come from https://trss.adoptium.net/resultSummary?parentId=66157115879917006ef59450

**Example D:**
[Test_openjdk22_hs_extended.openjdk_x86-64_alpine-linux](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_alpine-linux/25/) ⚠️ UNSTABLE ⚠️

[Test_openjdk22_hs_extended.openjdk_x86-64_alpine-linux_rerun](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_alpine-linux_rerun/8/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_nio_0,jdk_nio_1,jdk_jdi_0,jdk_build_0,jdk_build_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_alpine-linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=1&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk22u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk22u%2Fjdk22u-release-alpine-linux-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-22.0.0%2B0_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

**Example C**
[Test_openjdk22_hs_extended.openjdk_x86-64_linux](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_linux/27/) ⚠️ UNSTABLE ⚠️

[Test_openjdk22_hs_extended.openjdk_x86-64_linux_rerun](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_linux_rerun/5/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_tools_1,jdk_build_0,jdk_build_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=1&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk22u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk22u%2Fjdk22u-release-linux-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-22.0.0%2B0_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

java -version
[Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_0](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_0/4/) ⚠️ UNSTABLE ⚠️
[jdk_tools_1](https://trss.adoptium.net/output/test?id=66161be2879917006efd55b7) => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=66161be2879917006efd55b7) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66161acd879917006efd5393&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_0&testId=66161be2879917006efd55b7&testName=jdk_tools_1)
[jdk_build_0](https://trss.adoptium.net/output/test?id=66161be2879917006efd55b9) => [deep history 13/15 passed](https://trss.adoptium.net/deepHistory?testId=66161be2879917006efd55b9) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66161acd879917006efd5393&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_0&testId=66161be2879917006efd55b9&testName=jdk_build_0)

[Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_2](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_2/23/) ⚠️ UNSTABLE ⚠️
[jdk_build_1](https://trss.adoptium.net/output/test?id=66161bf9879917006efd5660) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66161bf9879917006efd5660) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66161acd879917006efd5398&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_linux_testList_2&testId=66161bf9879917006efd5660&testName=jdk_build_1)

**Example A**
[Test_openjdk22_hs_extended.openjdk_x86-64_mac](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_mac/19/) ⚠️ UNSTABLE ⚠️

[Test_openjdk22_hs_extended.openjdk_x86-64_mac_rerun](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_mac_rerun/4/) ✅ SUCCESS ✅
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST%3Djdk_net_1%2Cjdk_nio_1%2Cjdk_security3_1%2Cjdk_jfr_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=0&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk22u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk22u%2Fjdk22u-release-mac-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-22.0.0%2B0_adopt&LABEL_ADDITION=%21sw.os.osx.10_14&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

java -version
[Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_1](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_1/4/) ⚠️ UNSTABLE ⚠️
[jdk_security3_1](https://trss.adoptium.net/output/test?id=66168f25879917006e08dd5f) => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=66168f25879917006e08dd5f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66168dfb879917006e08d6df&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_1&testId=66168f25879917006e08dd5f&testName=jdk_security3_1)
[jdk_jfr_1](https://trss.adoptium.net/output/test?id=66168f25879917006e08dd71) => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=66168f25879917006e08dd71) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66168dfb879917006e08d6df&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_1&testId=66168f25879917006e08dd71&testName=jdk_jfr_1)

[Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_2](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_2/4/) ⚠️ UNSTABLE ⚠️
[jdk_net_1](https://trss.adoptium.net/output/test?id=66168f35879917006e08ddc7) => [deep history 7/8 passed](https://trss.adoptium.net/deepHistory?testId=66168f35879917006e08ddc7) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66168dfb879917006e08d6e1&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_2&testId=66168f35879917006e08ddc7&testName=jdk_net_1)
[jdk_nio_1](https://trss.adoptium.net/output/test?id=66168f35879917006e08ddc8) => [deep history 5/8 passed](https://trss.adoptium.net/deepHistory?testId=66168f35879917006e08ddc8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66168dfb879917006e08d6e1&buildName=Test_openjdk22_hs_extended.openjdk_x86-64_mac_testList_2&testId=66168f35879917006e08ddc8&testName=jdk_nio_1)

**Example B:**
[Test_openjdk22_hs_extended.openjdk_ppc64_aix](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_ppc64_aix/25/) ⚠️ UNSTABLE ⚠️

[Test_openjdk22_hs_extended.openjdk_ppc64_aix_rerun](https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_ppc64_aix_rerun/8/) ✅ SUCCESS ✅
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST%3Djdk_net_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=0&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=22&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk22u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk22u%2Fjdk22u-release-aix-ppc64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-22.0.0%2B0_adopt&LABEL_ADDITION=sw.os.aix.7_2&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

**Comment by sophia-guo** [comment]
Close this as most concerns have been resolved. 

The only one has no valid information anymore, if re happened can open a separate specific issue.

- [ ] rerun job shows unstable, however the TEST TARGETS SUMMARY shows passed. - might be issue with tkg with iteration >1? https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.system_x86-64_mac_rerun/1/
