### ISSUE TITLE
EPIC: Ensure test material is pinned to a specific tag and SHAs tracked

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5759]
There are several different repositories where we pull test material whose SHAs are not tracked in the TAP file, these include:
- [ ] Track perf benchmarks
- [ ] Track external test applications
- [ ] Track functional test material that is not from the openj9 project (i.e. rh-openjdk repos)
This refers mainly to material pulled in via ant scripts (build.xml files).  Any of the test material included in the [testenv.properties](https://github.com/adoptium/aqa-tests/blob/master/testenv/testenv.properties#L1-L34) file gets written to the TAP files.

In addition to tracking test material, we should also check that any dependencies introduced are also tracked / verified against a checksum to ensure it is transparent and clear what is being put onto test machines.  

Dependencies (any software that is pulled onto the machine during the test run) include:
- [prereqs](https://github.com/adoptium/aqa-tests/blob/master/doc/Prerequisites.md) that the Ansible playbooks install / or are defined in Dockerfiles 
- dependencies pulled in via [getDependency](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/getDependency) jobs

- [ ] Check for any scripts in test material used as part of the AQAvit targets that pull in dependencies opaquely.  
These are scripts outside of the mechanisms listed above (i.e. Ansible playbooks, getDependency list), without verification for a checksum, and especially if they are from unofficial or personal branches.  We should discourage the use of such scripts as it introduces a level of insecurity that we want to move away from.

**Comment by smlambert** [comment]
Likely related:
- https://github.com/adoptium/aqa-tests/issues/5288
- https://github.com/adoptium/aqa-tests/issues/5151

**Comment by sophia-guo** [comment]
Close this one as all test materials are tracked. The Dependencies  has a separate issue opened. https://github.com/adoptium/aqa-tests/issues/5954
